export enum CasapDisputeReason {
  "DisputeReasonUnAuth" = "DISPUTE_REASON_UNAUTH",
  "DisputeReasonMerchantIssue" = "DISPUTE_REASON_MERCHANT_ISSUE",
  "DisputeReasonATMIssue" = "DISPUTE_REASON_ATM_ISSUE",
  "DisputeReasonACHIssue" = "DISPUTE_REASON_ACH_ISSUE",
  "DisputeReasonTransferIssue" = "DISPUTE_REASON_TRANSFER_ISSUE",
  "DisputeReasonATMIssueCashNotDispensed" = "DISPUTE_REASON_ATM_ISSUE_CASH_NOT_DISPENSED",
  "DisputeReasonMerchantIssueGoodsOrServicesNotReceived" = "DISPUTE_REASON_MERCHANT_ISSUE_GOODS_OR_SERVICES_NOT_RECEIVED",
  "DisputeReasonMerchantIssueGoodsOrServicesNotAsDescribed" = "DISPUTE_REASON_MERCHANT_ISSUE_GOODS_OR_SERVICES_NOT_AS_DESCRIBED",
  "DisputeReasonMerchantIssueReturned" = "DISPUTE_REASON_MERCHANT_ISSUE_RETURNED",
  "DisputeReasonMerchantIssueCanceledSubscription" = "DISPUTE_REASON_MERCHANT_ISSUE_CANCELED_SUBSCRIPTION",
  "DisputeReasonMerchantIssueRefundNotReceived" = "DISPUTE_REASON_MERCHANT_ISSUE_REFUND_NOT_RECEIVED",
  "DisputeReasonMerchantIssueChargedIncorrectAmount" = "DISPUTE_REASON_MERCHANT_ISSUE_CHARGED_INCORRECT_AMOUNT",
  "DisputeReasonMerchantIssuePaidByOtherMeans" = "DISPUTE_REASON_MERCHANT_ISSUE_PAID_BY_OTHER_MEANS",
  "DisputeReasonTransferIssueNotReceived" = "DISPUTE_REASON_TRANSFER_ISSUE_NOT_RECEIVED",
  "DisputeReasonTransferIssueIncorrectRecipient" = "DISPUTE_REASON_TRANSFER_ISSUE_INCORRECT_RECIPIENT",
  "DisputeReasonTransferIssueIncorrectAmount" = "DISPUTE_REASON_TRANSFER_ISSUE_INCORRECT_AMOUNT",
  "DisputeReasonTransferIssueDuplicateCharge" = "DISPUTE_REASON_TRANSFER_ISSUE_DUPLICATE_CHARGE",
  "DisputeReasonATMIssuePartialCash" = "DISPUTE_REASON_ATM_ISSUE_PARTIAL_CASH",
  "DisputeReasonUnknown" = "DISPUTE_REASON_UNKNOWN",
}